core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.home, name='home'),
    path('del/<int:id>', views.todo_delete, name='delete'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout')

]

todo/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    text = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

todo/views.py
from django.contrib.auth import authenticate, alogin, login as authlogin, logout as authlogout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from .models import Todo
from django.shortcuts import redirect


# Create your views here.

@login_required(login_url='/login/')
def home(request):
    if request.method == 'POST':
        text = request.POST.get('text').strip()
        print(text)
        if text:
            Todo.objects.create(text=text, user=request.user)
        return redirect('/')
    if request.method == 'GET':
        todos = Todo.objects.filter(user=request.user).all()
        return render(request, 'todo/home.html', {'todos': todos})
    return render(request, 'todo/home.html')


def todo_delete(request, id):
    # todo = Todo.objects.get(id=id, user=request.user)
    todo = get_object_or_404(Todo, id=id, user=request.user)
    todo.delete()
    return redirect('/')


"""
 def todo_update(request, id):
    todo = get_object_or_404(Todo, id=id)
    if request.method == 'POST':
        text = request.POST.get('text').strip()
        if text:
            todo.text = text
            todo.save()
            return redirect('/')
    else:
        return render(request, 'todo/base.html', {'todo': todo})
"""


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username').strip()
        password = request.POST.get('password').strip()
        print(username)
        print(password)

        user = authenticate(username=username, password=password)
        if user is not None:
            authlogin(request, user)
            return redirect('todo:home')
        else:
            return render(request, 'todo/login.html', {'error': 'Invalid credentials'})
    return render(request, 'todo/login.html')


def logout(request):
    authlogout(request)
    return redirect('todo:login')

def signup(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    email = request.POST.get('email')

    print(username)
    if username and password and first_name and last_name and email:
        user = User.objects.create_user(username=username, password=password, first_name=first_name, last_name=last_name, email=email)
        user.save()
        return redirect('todo:login')

    return render(request, 'todo/signup.html')

todo/templates/todo/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            clifford: '#da373d',
          }
        }
      }
    }
  </script>
</head>
<body class="bg-gray-100">

<nav class="bg-blue-500 p-4">
    <div class="container mx-auto flex justify-between items-center">
        <a href="#" class="text-white font-bold text-xl">Todo App</a>

        <ul class="flex space-x-4">
            <li><a href="#" class="text-white">Home</a></li>
            <li><a href="#" class="text-white">Tasks</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'todo:logout' %}" class="text-white">Logout</a></li>
            {% else %}
                <li><a href="{% url 'todo:login' %}" class="text-white">Login</a></li>
                <li><a href="{% url 'todo:signup' %}" class="text-white">Register</a></li>
            {% endif %}          
        </ul>
    </div>
</nav>

{% block content %}
	
{% endblock %}


</html>

todo/templates/todo/home.html
{% extends "todo/base.html" %}

{% block content %}



    <div class="container mx-auto p-4">

        <!-- Your Todo App content goes here -->
        <h1 class="text-3xl font-bold mb-4">My Todo List</h1>
        <!-- Add your Todo list components and functionality here -->


        <div class="container mx-auto p-4">
            <div class="my-4">
                <form action="{% url 'todo:home' %}" method="post">
                    {% csrf_token %}
                    <label for="todoInput" class="sr-only">Add a new todo</label>
                    <input type="text" name="text" id="todoInput" class="w-3/4 p-2" placeholder="Add a new todo">
                    <button value="Submit" class="bg-blue-500 text-white px-4 py-2 ml-2" type="submit">Add Todo</button>
                </form>



            </div>

            {% for todo in todos %}
                <div class="bg-white mt-4 p-4 rounded shadow">
                    <div class="flex justify-between items-center">
                        <div class="flex items-center">
                            <label for="todoCheckbox" class="sr-only">Mark todo as completed</label>
                            <input type="checkbox" id="todoCheckbox" class="mr-2">
                            <span class="text-lg font-semibold">{{ todo.text }}</span>
                        </div>
                        <div class="flex space-x-2">

                            <div class="">


                            </div>

                            <div>
                                <a  class="text-slate-500">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" data-slot="icon" class="w-6 h-6">
                                        <path d="M21.731 2.269a2.625 2.625 0 0 0-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 0 0 0-3.712ZM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 0 0-1.32 2.214l-.8 2.685a.75.75 0 0 0 .933.933l2.685-.8a5.25 5.25 0 0 0 2.214-1.32l8.4-8.4Z" />
                                        <path d="M5.25 5.25a3 3 0 0 0-3 3v10.5a3 3 0 0 0 3 3h10.5a3 3 0 0 0 3-3V13.5a.75.75 0 0 0-1.5 0v5.25a1.5 1.5 0 0 1-1.5 1.5H5.25a1.5 1.5 0 0 1-1.5-1.5V8.25a1.5 1.5 0 0 1 1.5-1.5h5.25a.75.75 0 0 0 0-1.5H5.25Z" />
                                    </svg>

                                </a>
                            </div>


                            <div>
                                <a  class="text-slate-500" href="{% url 'todo:delete' todo.id %}"  >
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" data-slot="icon" class="w-5 h-5">
                                        <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 0 0 6 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 1 0 .23 1.482l.149-.022.841 10.518A2.75 2.75 0 0 0 7.596 19h4.807a2.75 2.75 0 0 0 2.742-2.53l.841-10.52.149.023a.75.75 0 0 0 .23-1.482A41.03 41.03 0 0 0 14 4.193V3.75A2.75 2.75 0 0 0 11.25 1h-2.5ZM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4ZM8.58 7.72a.75.75 0 0 0-1.5.06l.3 7.5a.75.75 0 1 0 1.5-.06l-.3-7.5Zm4.34.06a.75.75 0 1 0-1.5-.06l-.3 7.5a.75.75 0 1 0 1.5.06l.3-7.5Z" clip-rule="evenodd" />
                                    </svg>
                                </a>
                                <div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}


        </div>



    </div>
{% endblock %}

todo/templates/todo/login.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="bg-gray-100 flex items-center justify-center h-screen">

    <div class="bg-white p-8 rounded-lg  w-96">
        <h2 class="text-2xl font-semibold mb-6">Login</h2>

        <form method="post" action="{% url 'todo:login' %}">
            {% csrf_token %}
            <div class="mb-4">
                <label for="username" class="block text-gray-600 text-sm font-medium mb-2">Username</label>
                <input type="text" id="username" required name="username" class="w-full p-2 border border-gray-300 rounded focus:outline-none focus:border-blue-500">
            </div>

            <div class="mb-4">
                <label for="password" class="block text-gray-600 text-sm font-medium mb-2">Password</label>
                <input type="password" id="password" required name="password" class="w-full p-2 border border-gray-300 rounded focus:outline-none focus:border-blue-500">
            </div>

            <button type="submit" class="w-full bg-blue-500 text-white p-2 rounded hover:bg-blue-600 focus:outline-none">Login</button>
        </form>

            {% if error %}
                <div class="mt-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                    <strong class="font-bold">Error!</strong>
                    <span class="block sm:inline">{{ error }}</span>
                </div>
            {% endif %}
        <p class="mt-2">Do not  have an account? <a href="{% url 'todo:signup' %}" class="text-blue-500 hover:text-blue-600">Register</a></p>
    </div>
</div>
{% endblock %}

todo/templates/todo/signup.html
{% extends "todo/base.html" %}


{% block content %}

    <div class="flex items-center justify-center h-screen">
<div class="bg-white p-8 rounded-lg  w-96">
    <h2 class="text-3xl font-semibold text-center mb-6 text-gray-800">Create an Account</h2>

    <form class="" action="{% url 'todo:signup' %}" method="post">
        {% csrf_token %}
        <div class="mb-4">
            <label for="firstName" class="block text-sm font-medium text-gray-700 mb-2">First Name</label>
            <input type="text" id="firstName" name="first_name" class="w-full p-3 border border-gray-300 rounded focus:outline-none focus:border-blue-500" placeholder="Enter your first name">
        </div>

        <div class="mb-4">
            <label for="lastName" class="block text-sm font-medium text-gray-700 mb-2">Last Name</label>
            <input type="text" id="lastName" name="last_name" class="w-full p-3 border border-gray-300 rounded focus:outline-none focus:border-blue-500" placeholder="Enter your last name">
        </div>

        <div class="mb-4">
            <label for="username" class="block text-sm font-medium text-gray-700 mb-2">Username</label>
            <input type="text" id="username" name="username" class="w-full p-3 border border-gray-300 rounded focus:outline-none focus:border-blue-500" placeholder="Enter your last name">
        </div>


        <div class="mb-4">
            <label for="email" class="block text-sm font-medium text-gray-700 mb-2">Email</label>
            <input type="email" id="email" name="email" class="w-full p-3 border border-gray-300 rounded focus:outline-none focus:border-blue-500" placeholder="Enter your email">
        </div>

        <div class="mb-4">
            <label for="password" class="block text-sm font-medium text-gray-700 mb-2">Password</label>
            <input type="password" id="password" name="password" class="w-full p-3 border border-gray-300 rounded focus:outline-none focus:border-blue-500" placeholder="Enter your password">
        </div>


        <button type="submit" class="w-full bg-blue-500 text-white p-3 rounded hover:bg-blue-600 focus:outline-none">Register</button>
    </form>

    <p class="mt-4 text-sm text-gray-600 text-center">Already have an account? <a href="{% url 'todo:login' %}" class="text-blue-500">Login here</a>.</p>
</div>
    </div>
{% endblock content %}